---
name: File-pushd
version: 0.99
author:
  - 'David A Golden <dagolden@cpan.org>'
abstract: change directory temporarily for a limited scope
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Cwd: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  Test::More: 0.45
  perl: 5.004
provides:
  File::pushd:
    file: lib/File/pushd.pm
    version: 0.99
generated_by: Module::Build version 0.280501
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
