---
name: File-pushd
version: 0.10
author:
  - David A Golden <dagolden@cpan.org>
abstract: temporary chdir until File::pushd object goes out of scope
license: perl
requires:
  Test::More: 0.48
  perl: 5.005
provides:
  File::pushd:
    file: lib/File/pushd.pm
    version: 0.10
generated_by: Module::Build version 0.2702
