---
name: File-pushd
version: 1.00
author:
  - 'David A Golden <dagolden@cpan.org>'
abstract: change directory temporarily for a limited scope
license: apache
resources:
  license: http://apache.org/licenses/LICENSE-2.0
requires:
  Cwd: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  Test::More: 0.45
  perl: 5.004
provides:
  File::pushd:
    file: lib/File/pushd.pm
    version: 1.00
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
